version: '3.8'

services:
  web:
    build: .
    command: node index-db.js
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      MYSQL_DATABASE: nodeapp
      MYSQL_USER: nodeuser
      MYSQL_PASSWORD: mypass321
      MYSQL_HOST: db
      
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nodeapp
      MYSQL_USER: nodeuser
      MYSQL_PASSWORD: mypass321
      MYSQL_ROOT_PASSWORD: myrootpass321
