node 
{
   def git_commit_id

   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     git_commit_id = readFile('.git/commit-id').trim()
   }
   stage('Testing') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('Docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockercredentials') {
       def app = docker.build("maybellemo/node-jenkins-docker:${git_commit_id}", '.').push()
     }
   }
}